name: Deploy to production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v1
      - name: Install NPM dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy application
        run: npm run deploy
        env:
          APP_NAME: ${{ secrets.APP_NAME }}
          INSTANCE_NAME: production
          HOSTNAME: ${{ secrets.PRODUCTION_HOSTNAME }}
          SSL_CERT: ${{ secrets.PRODUCTION_SSL_CERT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
