name: Deploy to staging
on:
  push:
    branches:
      - staging
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - name: Install NPM dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy application
        run: npm run deploy
        env:
          SERVICE_NAME: staging
          HOSTNAME: ${{ secrets.STAGING_HOSTNAME }}
          SSL_CERT: ${{ secrets.STAGING_SSL_CERT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
