name: Deploy Pull Request environment
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - name: Install NPM dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy application
        run: npm run deploy
        env:
          HOSTNAME: pr-${{ github.event.number }}.${{ secrets.PULL_REQUEST_DOMAIN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Post comment with link to environment
        if: github.event.action == 'opened'
        uses: unsplash/comment-on-pr@master
        with:
          msg: "Deployed to https://pr-${{ github.event.number }}.${{ secrets.PULL_REQUEST_DOMAIN }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
