name: Delete Pull Request environment
on:
  pull_request:
    types: [closed]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      # We need to specify the master branch to checkout,
      # as otherwise this Workflow will fail, as it will
      # fail by default when a PR has just been closed!
      - uses: actions/checkout@master
        with:
          ref: refs/heads/master
      - uses: actions/setup-node@v1
      - name: Install NPM dependencies
        run: npm ci
      - name: Destroy instance of application
        run: npm run destroy
        env:
          HOSTNAME: pr-${{ github.event.number }}.${{ secrets.PULL_REQUEST_DOMAIN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
